// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC33Ci0vezGv_5fyjdFw6bZoK6ld7yRlU',
    appId: '1:833827681998:web:82097937064f0e4bff029f',
    messagingSenderId: '833827681998',
    projectId: 'laza-ef7a9',
    authDomain: 'laza-ef7a9.firebaseapp.com',
    storageBucket: 'laza-ef7a9.appspot.com',
    measurementId: 'G-H9BBQ8MN43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACozrqsZwMd_1L4QvUqaoAuLlQ4UYHXco',
    appId: '1:833827681998:android:fedc1cb93194041fff029f',
    messagingSenderId: '833827681998',
    projectId: 'laza-ef7a9',
    storageBucket: 'laza-ef7a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwT2Rl7MR7I1pjBrPtvYGxFuMNSFklwHQ',
    appId: '1:833827681998:ios:62691c418a71be99ff029f',
    messagingSenderId: '833827681998',
    projectId: 'laza-ef7a9',
    storageBucket: 'laza-ef7a9.appspot.com',
    iosBundleId: 'com.example.gradProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwT2Rl7MR7I1pjBrPtvYGxFuMNSFklwHQ',
    appId: '1:833827681998:ios:62691c418a71be99ff029f',
    messagingSenderId: '833827681998',
    projectId: 'laza-ef7a9',
    storageBucket: 'laza-ef7a9.appspot.com',
    iosBundleId: 'com.example.gradProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC33Ci0vezGv_5fyjdFw6bZoK6ld7yRlU',
    appId: '1:833827681998:web:2f4fbe97e2aca023ff029f',
    messagingSenderId: '833827681998',
    projectId: 'laza-ef7a9',
    authDomain: 'laza-ef7a9.firebaseapp.com',
    storageBucket: 'laza-ef7a9.appspot.com',
    measurementId: 'G-25YJMYXL6F',
  );

}